### ISSUE TITLE
XML resource error while building on cm-14.0 branch

### ISSUE THREAD

**Issue by IamTechknow** [CyanogenMod/android_device_lge_g3-common#3]
Hello, I looked into building CM 14 for the Verizon G3. While building I found the following error which ended my build:

`Resource at config_ui_blur_enabled appears in overlay but not in the base package; use
<add-resource> to add.`

It appears that in overlay/frameworks/base/core/res/res/values/config.xml there is a bool tag for "config_ui_blur_enabled" at the end of the file but there is no add-resource tag for it.

To fix the error, I added an add-resource tag right before the bool tag:

`<add-resource type="bool" name="config_ui_blur_enabled"></add-resource>`

And the build proceeds after that point. I do want to make sure this is fine however, I don't see any add-resource tags elsewhere.

**Comment by amdev01** [comment]
UI blur isn't supported in CM14.0 yet, simply delete this overlay and it'll be fine

**Comment by IamTechknow** [comment]
Thanks for the clarification. Since the tag isn't used yet, could you also comment it out until it is needed?

(Never mind, I'll fork the repo for myself and make my own changes)

**Comment by fixxnux** [comment]
To fix the error, I added an add-resource tag right before the bool tag:

<add-resource type="bool" name="config_ui_blur_enabled"></add-resource>

 Hey IamTechKnow, where did you add this piece of code?

**Comment by IamTechknow** [comment]
Right [here](https://github.com/IamTechknow/android_device_lge_g3-common/commit/2d9963f4f2b14eb2b808c09ce0db0f46b9ffed25), but not too relevant nowadays. Last time I built LineageOS 14.1 I didn't need to make such changes

**Comment by MaheshTechnicals** [comment]
I got that error can you guys tell me how to fix that - https://hastebin.com/egumuredeg.pl

I am building XenonHD 8.1.0 for mi max 2 device.
